from pathlib import Path

path = Path("src/local_coop_mobile.cc")
text = path.read_text(encoding="utf-8")

marker = "PHOBOI_CLOUDFLARE_ROUTE_V4"
if marker in text:
    print("PhoBoi Cloudflare route V4 already applied")
    raise SystemExit(0)

# V4 is deliberately layered on top of V3. V3 proves the local PhoBoi origin,
# sends complete HTTP responses, and keeps VPN addresses out of the public QR.
for required in (
    "PHOBOI_CLOUDFLARE_ROUTE_V3",
    "PHOBOI_CLOUDFLARE_PUBLIC_VERIFY_V2",
):
    if required not in text:
        raise SystemExit(f"Cloudflare V4 requires {required}")

# ---------------------------------------------------------------------------
# Quick Tunnel isolation.
# Cloudflare documents that account-less Quick Tunnels can fail when a normal
# ~/.cloudflared/config.yml or config.yaml exists. Do not rename or modify the
# user's config. Instead create an intentionally empty config in %TEMP% and
# explicitly point this child cloudflared process at it.
# ---------------------------------------------------------------------------
anchor = '''std::string mobileCloudflaredPath()\n{\n    char modulePath[MAX_PATH] {};'''
if anchor not in text:
    raise SystemExit("cloudflared path helper anchor missing")
helper = r'''// PHOBOI_CLOUDFLARE_ROUTE_V4
// PHOBOI_CLOUDFLARE_ISOLATED_CONFIG_V4
std::string mobileCloudflaredQuickConfigPath()
{
    char tempPath[MAX_PATH] {};
    DWORD length = GetTempPathA(MAX_PATH, tempPath);
    if (length == 0 || length >= MAX_PATH) {
        debugPrint("[PHOBOI MOBILE] Cloudflare V4 could not resolve TEMP for isolated Quick Tunnel config\n");
        return "";
    }

    std::string path(tempPath, length);
    if (!path.empty() && path.back() != '\\' && path.back() != '/') {
        path.push_back('\\');
    }
    path += "phoboi-cloudflared-empty.yml";

    HANDLE file = CreateFileA(
        path.c_str(),
        GENERIC_WRITE,
        FILE_SHARE_READ,
        nullptr,
        CREATE_ALWAYS,
        FILE_ATTRIBUTE_TEMPORARY,
        nullptr);
    if (file == INVALID_HANDLE_VALUE) {
        debugPrint("[PHOBOI MOBILE] Cloudflare V4 isolated config create failed winerr=%lu\n", GetLastError());
        return "";
    }

    const char contents[] = "# PhoBoi Quick Tunnel - intentionally empty\r\n";
    DWORD written = 0;
    BOOL ok = WriteFile(file, contents, static_cast<DWORD>(sizeof(contents) - 1), &written, nullptr);
    CloseHandle(file);
    if (!ok || written != sizeof(contents) - 1) {
        DeleteFileA(path.c_str());
        debugPrint("[PHOBOI MOBILE] Cloudflare V4 isolated config write failed\n");
        return "";
    }

    return path;
}

'''
text = text.replace(anchor, helper + anchor, 1)

# V3 forced HTTP/2. Cloudflare's current guidance is to let cloudflared select
# the usable transport: QUIC when UDP works, HTTP/2/TCP when it does not. A VPN
# can permit only one of those. Keep the origin fixed to IPv4 loopback, but let
# the edge transport negotiate automatically and isolate Quick Tunnel config.
old_command = '    std::string commandText = "\\\"" + executable + "\\\" tunnel --no-autoupdate --protocol http2 --loglevel info --url http://127.0.0.1:27888"; // PHOBOI_CLOUDFLARE_HTTP2_V3'
new_command = r'''    // PHOBOI_CLOUDFLARE_AUTO_PROTOCOL_V4
    std::string quickConfig = mobileCloudflaredQuickConfigPath();
    std::string commandText = "\"" + executable + "\" tunnel --no-autoupdate --protocol auto --loglevel info";
    if (!quickConfig.empty()) {
        commandText += " --config \"" + quickConfig + "\"";
    }
    commandText += " --url http://127.0.0.1:27888";
    debugPrint("[PHOBOI MOBILE] Cloudflare V4 transport=auto isolated_config=%d\n", quickConfig.empty() ? 0 : 1);'''
if old_command not in text:
    raise SystemExit("V3 cloudflared command anchor missing")
text = text.replace(old_command, new_command, 1)

# ---------------------------------------------------------------------------
# Do NOT perform the public HTTPS probe in cloudflared's stdout reader thread.
# V2 blocked ReadFile for several seconds, which hid the exact cloudflared logs
# generated by the failing public request. V4 keeps the reader draining output
# continuously and verifies the public URL in a detached, URL-scoped worker.
# It also allows a much longer DNS/edge warm-up window because TryCloudflare
# hostnames are ephemeral and can take time to become externally resolvable.
# ---------------------------------------------------------------------------
old_block = r'''            if (!candidateHandled && edgeRegistered && !candidateUrl.empty()) {
                candidateHandled = true;
                {
                    // PHOBOI_CLOUDFLARE_EDGE_READY_FALLBACK_V2
                    // Cloudflare documents a registered connector as the tunnel
                    // being active. Publish the URL now instead of letting a
                    // host-side WinHTTP/VPN/proxy false-negative hide the QR.
                    std::lock_guard<std::mutex> lock(gCloudflareStateMutex);
                    gCloudflarePublicUrl = candidateUrl;
                    gCloudflareStatus = "READY - EDGE CONNECTED";
                }

                bool reachable = false;
                for (int attempt = 0; attempt < 8 && !reachable; attempt++) {
                    // Let TryCloudflare DNS/route propagation settle after the
                    // connector registration before each bounded self-probe.
                    if (attempt != 0) Sleep(750);
                    reachable = mobileVerifyCloudflarePublicHealth(candidateUrl);
                }

                {
                    std::lock_guard<std::mutex> lock(gCloudflareStateMutex);
                    // PHOBOI_CLOUDFLARE_NONBLOCKING_SELF_CHECK_V2
                    // A successful /health is stronger evidence. A failed host
                    // self-check is explicitly inconclusive and must not turn a
                    // registered Quick Tunnel into permanent UNREACHABLE.
                    gCloudflarePublicUrl = candidateUrl;
                    gCloudflareStatus = reachable
                        ? "READY - PUBLIC VERIFIED"
                        : "READY - EDGE CONNECTED";
                }
                debugPrint("[PHOBOI MOBILE] public tunnel V2 url=%s edge=1 self_probe=%d\n",
                    candidateUrl.c_str(), reachable ? 1 : 0);
            }'''
new_block = r'''            if (!candidateHandled && edgeRegistered && !candidateUrl.empty()) {
                candidateHandled = true;
                const std::string verifyUrl = candidateUrl;
                {
                    // PHOBOI_CLOUDFLARE_ASYNC_VERIFY_V4
                    std::lock_guard<std::mutex> lock(gCloudflareStateMutex);
                    gCloudflarePublicUrl = verifyUrl;
                    gCloudflareStatus = "EDGE CONNECTED - PUBLIC WARMUP";
                }
                debugPrint("[PHOBOI MOBILE] Cloudflare V4 edge registered url=%s; public warmup started\n",
                    verifyUrl.c_str());

                std::thread([verifyUrl]() {
                    bool reachable = false;
                    // PHOBOI_CLOUDFLARE_LONG_WARMUP_V4
                    // Keep trying for 90 seconds. Stop immediately if RESET/NEW
                    // LINK has replaced this URL, so stale verifiers cannot win.
                    for (int attempt = 0; attempt < 90 && !reachable; attempt++) {
                        {
                            std::lock_guard<std::mutex> lock(gCloudflareStateMutex);
                            if (gCloudflarePublicUrl != verifyUrl) {
                                return;
                            }
                        }
                        reachable = mobileVerifyCloudflarePublicHealth(verifyUrl);
                        if (!reachable) {
                            if (attempt == 4 || attempt == 14 || attempt == 29 || attempt == 59) {
                                debugPrint("[PHOBOI MOBILE] Cloudflare V4 public warmup url=%s elapsed=%ds not-ready-yet\n",
                                    verifyUrl.c_str(), attempt + 1);
                            }
                            Sleep(1000);
                        }
                    }

                    std::lock_guard<std::mutex> lock(gCloudflareStateMutex);
                    if (gCloudflarePublicUrl != verifyUrl) {
                        return;
                    }
                    if (reachable) {
                        gCloudflareStatus = "READY - PUBLIC VERIFIED";
                        debugPrint("[PHOBOI MOBILE] Cloudflare V4 PUBLIC VERIFIED url=%s\n", verifyUrl.c_str());
                    } else {
                        // Keep the URL visible because an edge-connected tunnel
                        // may still be reachable from the phone even when the
                        // host's VPN/DNS path cannot self-probe it.
                        gCloudflareStatus = "EDGE CONNECTED - PUBLIC UNVERIFIED";
                        debugPrint("[PHOBOI MOBILE] Cloudflare V4 public verification timed out after 90s url=%s\n",
                            verifyUrl.c_str());
                    }
                }).detach();
            }'''
if old_block not in text:
    raise SystemExit("Cloudflare V2 synchronous verification block missing")
text = text.replace(old_block, new_block, 1)

# V3 logged only error-ish chunks. During public warmup we need Cloudflare's own
# startup/registration lines too, otherwise a successful edge registration and
# protocol choice remain invisible in the game log.
old_log = r'''            if (cloudflareChunk.find("ERR") != std::string::npos
                || cloudflareChunk.find("WRN") != std::string::npos
                || cloudflareChunk.find("502") != std::string::npos
                || cloudflareChunk.find("connection refused") != std::string::npos) {
                debugPrint("[PHOBOI CLOUDFLARED] %s\n", cloudflareChunk.c_str());
            }'''
new_log = r'''            // PHOBOI_CLOUDFLARED_STARTUP_LOG_V4
            if (cloudflareChunk.find("INF") != std::string::npos
                || cloudflareChunk.find("ERR") != std::string::npos
                || cloudflareChunk.find("WRN") != std::string::npos
                || cloudflareChunk.find("502") != std::string::npos
                || cloudflareChunk.find("connection refused") != std::string::npos) {
                debugPrint("[PHOBOI CLOUDFLARED] %s\n", cloudflareChunk.c_str());
            }'''
if old_log not in text:
    raise SystemExit("V3 cloudflared diagnostic logger anchor missing")
text = text.replace(old_log, new_log, 1)

for required in (
    "PHOBOI_CLOUDFLARE_ROUTE_V4",
    "PHOBOI_CLOUDFLARE_ISOLATED_CONFIG_V4",
    "PHOBOI_CLOUDFLARE_AUTO_PROTOCOL_V4",
    "PHOBOI_CLOUDFLARE_ASYNC_VERIFY_V4",
    "PHOBOI_CLOUDFLARE_LONG_WARMUP_V4",
    "PHOBOI_CLOUDFLARED_STARTUP_LOG_V4",
):
    if required not in text:
        raise SystemExit(f"missing Cloudflare route V4 marker {required}")

path.write_text(text, encoding="utf-8")
print("Applied Cloudflare V4 isolated Quick Tunnel config, auto transport, async verification, long warmup, and full startup diagnostics")
